### ISSUE TITLE
Program gets stuck in windup mode

### ISSUE THREAD

**Issue by memecian** [memecian/sis-gleiter#2]

**Comment by hibbes** [comment]
Evt verursacht der Servolenkung Lastspitzen und bringt den Arduino so zum Absturz. Hatte das mal an den Arduino-Flugzeugen. Abhilfe: Kondensator in den Stromkreis klemmen, der das wegbuffert.

**Comment by memecian** [comment]
Kann natürlioch auch sein, dass der Button falsch angeschlossen ist, müssen wir noch überprüfen.

**Comment by memecian** [comment]
Das war alles nur ein Programmfehler 🤦🏼‍♂
